-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 12:55:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_theme` (
  `id tb_theme` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id tb_theme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_users` (
  `id tb_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(45) NULL,
  PRIMARY KEY (`id tb_users`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_posts` (
  `id tb_posts` INT NOT NULL AUTO_INCREMENT,
  `tittle` VARCHAR(255) NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `data` DATE NULL,
  `tb_theme_idtb_theme` INT NOT NULL,
  `tb_users_id tb_users` INT NOT NULL,
  PRIMARY KEY (`id tb_posts`),
  INDEX `fk_tb_posts_tb_theme_idx` (`tb_theme_idtb_theme` ASC) VISIBLE,
  INDEX `fk_tb_posts_tb_users1_idx` (`tb_users_id tb_users` ASC) VISIBLE,
  CONSTRAINT `fk_tb_posts_tb_theme`
    FOREIGN KEY (`tb_theme_idtb_theme`)
    REFERENCES `mydb`.`tb_theme` (`id tb_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_posts_tb_users1`
    FOREIGN KEY (`tb_users_id tb_users`)
    REFERENCES `mydb`.`tb_users` (`id tb_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
